/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/advertisement': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Получить список объявлений */
        get: {
            parameters: {
                query?: {
                    userId?: number
                    limit?: number
                    offset?: number
                }
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Список объявлений */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            items?: components['schemas']['Advertisement'][]
                            total?: number
                            limit?: number
                            offset?: number
                        }
                    }
                }
            }
        }
        put?: never
        /** Создать объявление */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody: {
                content: {
                    'multipart/form-data': {
                        name: string
                        description: string
                        price: number
                        city: string
                        images?: string[]
                    }
                }
            }
            responses: {
                /** @description Объявление создано */
                201: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['Advertisement']
                    }
                }
                /** @description Не авторизован */
                401: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/advertisement/{id}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Получить объявление по ID */
        get: {
            parameters: {
                query?: never
                header?: never
                path: {
                    id: number
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Объявление */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['Advertisement']
                    }
                }
                /** @description Не найдено */
                404: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        put?: never
        post?: never
        /** Удалить объявление */
        delete: {
            parameters: {
                query?: never
                header?: never
                path: {
                    id: number
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Удалено */
                204: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                /** @description Не авторизован */
                401: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                /** @description Не найдено */
                404: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        options?: never
        head?: never
        /** Обновить объявление */
        patch: {
            parameters: {
                query?: never
                header?: never
                path: {
                    id: number
                }
                cookie?: never
            }
            requestBody?: {
                content: {
                    'application/json': {
                        name?: string
                        description?: string
                        price?: number
                        city?: string
                    }
                }
            }
            responses: {
                /** @description Обновлено */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['Advertisement']
                    }
                }
                /** @description Не авторизован */
                401: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                /** @description Не найдено */
                404: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        trace?: never
    }
    '/auth/register': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /** Регистрация пользователя */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': {
                        email: string
                        password: string
                        username: string
                    }
                }
            }
            responses: {
                /** @description Пользователь зарегистрирован */
                201: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['AuthResponse']
                    }
                }
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/auth/login': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /** Авторизация пользователя */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': {
                        /** @example test@mail.com */
                        email: string
                        /** @example 123456 */
                        password: string
                    }
                }
            }
            responses: {
                /** @description Успешный вход */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['AuthResponse']
                    }
                }
                /** @description Неверные данные */
                401: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/profile/{id}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Получить профиль пользователя */
        get: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description ID пользователя */
                    id: number
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Успешно получен профиль */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['Profile']
                    }
                }
                /** @description Не авторизован */
                401: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                /** @description Пользователь не найден */
                404: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        /** Обновить профиль пользователя */
        patch: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description ID пользователя */
                    id: number
                }
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': {
                        username?: string
                        lastName?: string | null
                        city?: string | null
                        phone?: string | null
                        avatar?: string | null
                    }
                }
            }
            responses: {
                /** @description Профиль успешно обновлён */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['Profile']
                    }
                }
                /** @description Ошибка валидации */
                400: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                /** @description Не авторизован */
                401: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                /** @description Пользователь не найден */
                404: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        trace?: never
    }
    '/reviews': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /** Создать отзыв */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': {
                        text: string
                        rating: number
                        advertisementId: number
                    }
                }
            }
            responses: {
                /** @description Отзыв создан */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['Review']
                    }
                }
                /** @description Не авторизован */
                401: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/reviews/comment/{id}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Получить отзывы по объявлению */
        get: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description ID объявления */
                    id: number
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Список отзывов */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            items?: components['schemas']['Review'][]
                            total?: number
                            page?: number
                            limit?: number
                        }
                    }
                }
            }
        }
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/seller/{sellerId}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Получить профиль продавца */
        get: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description ID продавца */
                    sellerId: number
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Профиль продавца */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['Seller']
                    }
                }
                /** @description Продавец не найден */
                404: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/seller/{sellerId}/advertisements': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Получить объявления продавца */
        get: {
            parameters: {
                query?: {
                    /** @description Количество элементов */
                    limit?: number
                    /** @description Смещение (для пагинации) */
                    offset?: number
                }
                header?: never
                path: {
                    /** @description ID продавца */
                    sellerId: number
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Список объявлений продавца */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            items?: components['schemas']['Advertisement'][]
                            total?: number
                            limit?: number
                            offset?: number
                        }
                    }
                }
                /** @description Продавец не найден */
                404: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
}
export type webhooks = Record<string, never>
export interface components {
    schemas: {
        AuthResponse: {
            success?: boolean
            message?: string
            token?: string
            user?: components['schemas']['Profile']
        }
        Profile: {
            id?: number
            username?: string
            lastName?: string | null
            email?: string
            city?: string | null
            phone?: string | null
            avatar?: string | null
            /** Format: date-time */
            createdAt?: string
        }
        Seller: {
            id?: number
            username?: string
            city?: string | null
            /** Format: date-time */
            createdAt?: string
        }
        Review: {
            id: number
            text: string
            rating: number
            advertisementId: number
            userId: number
            /** Format: date-time */
            createdAt: string
            user?: {
                username?: string
                avatar?: string | null
            }
        }
        Advertisement: {
            id: number
            name: string
            description: string
            price: number
            city: string
            images: string[]
            userId: number
            reviewsCount?: number
            /** Format: date-time */
            createdAt: string
            /** Format: date-time */
            updatedAt?: string
        }
    }
    responses: never
    parameters: never
    requestBodies: never
    headers: never
    pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
