export const catalogMockState = {
    catalog: {
        items: [
            {
                id: 1,
                name: 'Fantastic Gold Bike',
                description: 'Очень хороший велосипед',
                price: 72769,
                city: 'Санкт-Петербург',
                createdAt: new Date().toISOString(),
                images: ['https://picsum.photos/300/200?1'],
                userId: 1,
            },
            {
                id: 2,
                name: 'Awesome Concrete Hat',
                description: 'Классная шляпа',
                price: 57864,
                city: 'Санкт-Петербург',
                createdAt: new Date().toISOString(),
                images: ['https://picsum.photos/300/200?2'],
                userId: 1,
            },
            {
                id: 3,
                name: 'Intelligent Concrete Cheese',
                description: 'Качественный товар по хорошей цене.',
                price: 20295,
                city: 'Санкт-Петербург',
                createdAt: new Date().toISOString(),
                images: ['https://picsum.photos/300/200?3'],
                userId: 1,
            },
            {
                id: 4,
                name: 'Recycled Wooden Bacon',
                description: 'Практически новый товар.',
                price: 36072,
                city: 'Санкт-Петербург',
                createdAt: new Date().toISOString(),
                images: ['https://picsum.photos/300/200?4'],
                userId: 1,
            },
            {
                id: 5,
                name: 'Intelligent Concrete Cheese',
                description: 'Надёжный и качественный товар.',
                price: 19295,
                city: 'Санкт-Петербург',
                createdAt: new Date().toISOString(),
                images: ['https://picsum.photos/300/200?5'],
                userId: 1,
            },
            {
                id: 6,
                name: 'Intelligent Concrete Cheese',
                description: 'Отличное состояние.',
                price: 20895,
                city: 'Санкт-Петербург',
                createdAt: new Date().toISOString(),
                images: ['https://picsum.photos/300/200?6'],
                userId: 1,
            },
            {
                id: 7,
                name: 'Intelligent Concrete Cheese',
                description: 'Недорогой вариант.',
                price: 205,
                city: 'Санкт-Петербург',
                createdAt: new Date().toISOString(),
                images: ['https://picsum.photos/300/200?7'],
                userId: 1,
            },
            {
                id: 8,
                name: 'Intelligent Concrete Cheese',
                description: 'Почти не использовался.',
                price: 30295,
                city: 'Санкт-Петербург',
                createdAt: new Date().toISOString(),
                images: ['https://picsum.photos/300/200?8'],
                userId: 1,
            },
        ],
        total: 120,
        page: 1,
        isLoading: false,
        error: null,
    },
}
