export const catalogMockState = {
    catalog: {
        items: [
            {
                id: '1',
                name: 'Fantastic Gold Bike',
                price: 72769,
                city: 'Санкт-Петербург',
                createdAt: 'Сегодня',
                images: ['https://picsum.photos/300/200?1'],
            },
            {
                id: '2',
                name: 'Awesome Concrete Hat',
                price: 57864,
                city: 'Санкт-Петербург',
                createdAt: 'Сегодня',
                images: ['https://picsum.photos/300/200?2'],
            },
            {
                id: '3',
                name: 'Intelligent Concrete Cheese',
                price: 20295,
                city: 'Санкт-Петербург',
                createdAt: 'Сегодня',
                images: ['https://picsum.photos/300/200?3'],
            },
            {
                id: '4',
                name: 'Recycled Wooden Bacon',
                price: 36072,
                city: 'Санкт-Петербург',
                createdAt: 'Сегодня',
                images: ['https://picsum.photos/300/200?4'],
            },
            {
                id: '5',
                name: 'Intelligent Concrete Cheese',
                price: 19295,
                city: 'Санкт-Петербург',
                createdAt: 'Сегодня',
                images: ['https://picsum.photos/300/200?5'],
            },
            {
                id: '6',
                name: 'Intelligent Concrete Cheese',
                price: 20895,
                city: 'Санкт-Петербург',
                createdAt: 'Сегодня',
                images: ['https://picsum.photos/300/200?6'],
            },
            {
                id: '7',
                name: 'Intelligent Concrete Cheese',
                price: 205,
                city: 'Санкт-Петербург',
                createdAt: 'Сегодня',
                images: ['https://picsum.photos/300/200?7'],
            },
            {
                id: '8',
                name: 'Intelligent Concrete Cheese',
                price: 30295,
                city: 'Санкт-Петербург',
                createdAt: 'Сегодня',
                images: ['https://picsum.photos/300/200?8'],
            },
        ],
        total: 120,
        page: 1,
        isLoading: false,
        error: null,
    },
}
