export const sellerMockState = {
    seller: {
        profile: {
            id: 1,
            username: 'Bert',
            city: 'West Rosina',
            avatar: null,
            createdAt: '2021-08-01',
        },

        advertisements: [
            {
                id: 1,
                name: 'Frozen Granite Computer',
                description: 'Очень хороший компьютер',
                price: 84561,
                city: 'Санкт-Петербург',
                createdAt: 'Сегодня',
                images: ['https://picsum.photos/300/200?1'],
                userId: 1,
            },
            {
                id: 2,
                name: 'Elegant Ceramic Shirt',
                description: 'Стильная рубашка',
                price: 80763,
                city: 'Санкт-Петербург',
                createdAt: 'Сегодня',
                images: ['https://picsum.photos/300/200?2'],
                userId: 1,
            },
            {
                id: 3,
                name: 'Modern Granite Sausages',
                description: 'Вкусные сосиски',
                price: 42660,
                city: 'Санкт-Петербург',
                createdAt: 'Сегодня',
                images: ['https://picsum.photos/300/200?3'],
                userId: 1,
            },
            {
                id: 4,
                name: 'Tasty Silk Chair',
                description: 'Удобный стул',
                price: 83203,
                city: 'Санкт-Петербург',
                createdAt: 'Сегодня',
                images: ['https://picsum.photos/300/200?4'],
                userId: 1,
            },
        ],
        total: 4,
        page: 1,
        isProfileLoading: false,
        isAdvertisementsLoading: false,
        error: null,
    },
}
